Update cicd.yml

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -91,7 +91,16 @@ jobs:
         run: |
           IMAGE_TAG=${{ needs.build-and-push.outputs.sha }}
           LS_PATH=$([[ $GITHUB_REF == refs/heads/dev ]] && echo $DEV_PATH || echo $PROD_PATH)
-          sed -i "s|newTag: .*|newTag: $IMAGE_TAG|" $LS_PATH
-          git add .
-          git commit -m "Update image version to $IMAGE_TAG"
-          git push
+          
+          # Check if the file exists
+          if [ -f "$LS_PATH" ]; then
+            sed -i "s|newTag: .*|newTag: $IMAGE_TAG|" "$LS_PATH"
+            git add "$LS_PATH"
+            git commit -m "Update image version to $IMAGE_TAG"
+            git push
+          else
+            echo "Error: $LS_PATH does not exist."
+            exit 1
+          fi
+
+
